### ISSUE TITLE
jscs warning when building the boiler plate code

### ISSUE THREAD

**Issue by ashishkumarshah** [t1st3/generator-amd#40]
Hello Maintainers,

I get this error when i try to build the generated boiler plate code. I tried searching the source code for any usage of Vow but I couldn't find anything.

Workaround: If i build with --force, everything works. 
______________________________________________________________
grunt jscs
Running "jscs:src" (jscs) task
Warning: Vow.promise is not a function Use --force to continue.

Aborted due to warnings.

Thanks for your time!

**Comment by t1st3** [comment]
@ashishkumarshah just fixed this issue; this will land in next release (due shortly). Thanks for reporting this.
